name: zona_provider_main
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^4.0.1
  auto_size_text: ^3.0.0
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.1
  curl_logger_dio_interceptor: ^0.0.3
  dartz: ^0.10.1
  dio: ^4.0.6
  easy_localization: ^3.0.1
  flutter_bloc: ^8.0.1
  flutter_gen: ^4.2.1
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  injectable: ^1.5.3
  internet_connection_checker: ^0.0.1+4
  intl: ^0.17.0
  json_annotation: ^4.5.0
  logger: ^1.1.0
  percent_indicator: ^4.2.2
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.15
  pull_to_refresh: ^2.0.0
  shimmer: ^2.0.0
  jwt_decoder: ^2.0.1
  image_picker: ^0.8.5+3
  dots_indicator: ^2.0.0
  flutter_svg: ^1.1.4
  form_field_validator: ^1.1.0
  intl_phone_number_input: ^0.7.0+2
  responsive_framework: ^0.1.8
  http_parser: ^4.0.1
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.2.1
  flutter_native_splash: ^2.1.3+1
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.5
  retrofit_generator: ^4.0.1
  flutter_localizations:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appstore.jpg"
  remove_alpha_ios: true
flutter_gen:
  output: lib/presentation/core/utils/generated_assets/
  integrations:
    flutter_svg: true
flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/images/onboarding/